weights: ''
cfg: MedYOLO/models3D/yolo3Ds.yaml
data: MedYOLO/data/example.yaml
hyp: MedYOLO/data/hyps/hyp.finetune.yaml
epochs: 50
batch_size: 16
imgsz: 350
resume: false
nosave: false
noval: true
noautoanchor: false
evolve: null
image_weights: false
device: ''
single_cls: false
adam: true
workers: 16
project: MedYOLO/runs/train
name: exp
exist_ok: false
label_smoothing: 0.0
patience: 200
freeze: 0
save_period: 1
local_rank: -1
norm: CT
file_format: auto
no_checkpoint: false
checkpoint_retries: 3
save_only_last: false
save_dir: MedYOLO/runs/train/exp
